name: Using reusable workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Instal dependencies
        run: npm ci
      - name:  Lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Instal dependencies
        run: npm ci
      - name:  Test code
        run: npm run test

  deploy:
    needs: test
    uses: ./.github/workflows/reusable.yml
      