name: Matrix Demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [20,21,22]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix.operating-system}}
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/set-up-node@v3
              with:
                node-version: ${{matrix.node-version}}
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
